### ISSUE TITLE
User can turn their car.

### ISSUE THREAD

**Issue by addy-abid** [AddyAbid/driving-game#2]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x] Query car in JS file
- [x] Listen for keyDown event on document
- [x] Create data.js file
- [x] Add data model that shows the direction in which the car is facing
- [x] Add key codes accordingly to turn car in all directions
- [x] Update data model to show which direction the car is facing
