### ISSUE TITLE
User can start their car.

### ISSUE THREAD

**Issue by addy-abid** [AddyAbid/driving-game#3]
## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

## ✅ Task List

- [x] Set cars position value to absolute
- [x] Add car location values to data model
- [x] Style car to change top and left box offset
- [x] Create function to move car by pressing spacebar
- [x] Set Interval to call moving car function
- [x] Update data model location values as the car moves
