### ISSUE TITLE
User can stop their car.

### ISSUE THREAD

**Issue by addy-abid** [AddyAbid/driving-game#4]
## 💰 Motivation

If the user cannot stop their car, it goes off the page.

## 📐 Plan

Stop the car if the user presses space again.

## ✅ Task List

- [x] Add boolean value to data model indicating whether the car is on or off
- [x] Update data model for when car starts and stops
- [x] If user presses space a second time, clear interval
