### ISSUE TITLE
User can steer their car

### ISSUE THREAD

**Issue by addy-abid** [AddyAbid/driving-game#5]
## 💰 Motivation

Our game needs MAXIMUM realism to be immersive 😂.

## 📐 Plan

Change the car's location based on which direction it is facing.

## ✅ Task List

- [x] Add variable for moving car up and down
- [ ] Create function for arrow up event
- [ ] Create function for arrow down event
- [ ] If arrow down event, decrease car's y coordinate and update data model
- [ ] if arrow up event, increase car's y coordinate and update data model
